### ISSUE TITLE
high-level documentation for client_pool is missing

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/drool#64]
Hello,

after reading files src/drool.1 and src/drool.conf.5 is not clear what `client_pool` is and how it should be used.

Maybe some high-level description of terms would help. The questions I'm unable to answer are for example:
- Can it send packets to multiple target ("server") addresses?
- Will it want for reply from all of them before continuing with next query?

Thank you for explanation!

**Comment by jelu** [comment]
The reason that the documentation is vague is because the logic is not really complete yet, for example should `drool` have the ability to run different configurations / setups or just one? That impacts design quite a bit even if I've tried to build it as modular as possible.

To answer your questions for the current 1.0.0-beta.3 version:
- No, it can't do that yet.
- The simulated client will wait for any bits back until doing the next query. This behavior can be changed by specifying `client_pool skip_reply;`. Multiple simulated clients can run simultaneously.

**Comment by jelu** [comment]
@pspacek What do you think about #72 ?
