### ISSUE TITLE
too strict warnings about timing

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/drool#74]
Hello,

first of all, thank you for drool, I like :-)

I'm using it to replay traffic from PCAP to a resolver and I get several warning messages a second. The warnings look like this:

```
2017-08-13 08:24:31 callback.c:0237 network warning: Unable to keep up with timings (process cost 0.000070860, packet diff 0.000001, now 6737431.188798957, sleep to 6737431.188658237)
```

If I understand it correctly, drool is warning me that the replay process is about 1 microsecond delayed in comparison with the source PCAP file. It seems to me too strict because 1 microsecond precision on ordinary HW and kernel is still a respectable timing :-)

I suggest to loose the check, or even better make it configurable. For my use-case even 1 second would be good enough.

Also, I'm not sure how I should interpret the `now 6737431.188798957, sleep to 6737431.188658237` part of the message. Does it mean that the process is already 1 microsecond late but it is going to sleep 140.72 more microseconds? My naive expectation is that if the process is "late" it will send the packet right away without further delay.

That could be the effect of the new tunable: If delay is smaller than X send the packet right away (i.e. "try to catch up"), if the delay is longer than X do something more intelligent.

Thank you for considering this!

**Comment by jelu** [comment]
Sorry that the output is very debugish, I will try and explain here and then add it to the documentation.

- `process cost`: This is the CPU cost of processing the packet including the cost of measuring the cost
- `packet diff`: This is the timing diff between the previous packet and the packet being processed as seen from the PCAP, i.e. the time to wait before sending it
- `now`: Is the time "now" or at least when the processing for this packet begun
- `sleep to`: Was the time it should have slept to (since this warning we missed it)

> If I understand it correctly, drool is warning me that the replay process is about 1 microsecond delayed in comparison with the source PCAP file.

No, the cost of processing (7e-5) is a lot higher then the diff (1e-6) so it can't send it when it should.

> Also, I'm not sure how I should interpret the now 6737431.188798957, sleep to 6737431.188658237 part of the message. Does it mean that the process is already 1 microsecond late but it is going to sleep 140.72 more microseconds?

`now` should not be higher then `sleep to`, which it is here and means that it ran passed the time to send the packet.

> That could be the effect of the new tunable: If delay is smaller than X send the packet right away (i.e. "try to catch up"), if the delay is longer than X do something more intelligent.

I think the quickest and easiest fix here is to add a option to just try the best you can to keep up with the timings. I'll poke at the code some now and give you a branch to test.

Thanks for using it and reporting :)

**Comment by jelu** [comment]
@pspacek can you test my `besteff` branch?
```
git remote add jelu https://github.com/jelu/drool.git
git fetch --all
git checkout besteff
```

**Comment by pspacek** [comment]
I tried that and all I can say is that is does not spit warnings anymore :-)

Number of queries per second received by the SW under test did not change noticeably which is kind of expected because number of warnings per second is small when compared with number of queries per second.

**Comment by jelu** [comment]
Thanks for testing!

**Comment by pspacek** [comment]
Hmm, is it possible to combine timing multiply 0.5 + timing best_effort?
